server:
  port: 9010

# --- Spring AI Configuration for Vertex AI Gemini ---
spring:
  ai:
    vertex:
      ai:
        gemini:
          # Your Google Cloud Project ID
          project-id: "gen-lang-client-0096077484"
          # The region for your project, e.g., us-central1
          location: "asia-south1"
          chat:
            options:
              # Using a fast and cost-effective model
              model: gemini-2.5-flash
              
# --- Google API Key Configuration ---
# This is now a separate top-level property
google:
  api-key: ${GOOGLE_API_KEY:paste-your-key-here-for-local-use-ONLY-if-repo-is-private}
