server:
  port: 9010

# --- Spring AI Configuration for Google AI Gemini ---
spring:
  ai:
    google:
      gemini:
        # This tells Spring to look for an environment variable named GOOGLE_API_KEY.
        api-key: ${GOOGLE_API_KEY}
        chat:
          options:
            # The model name is configurable and can be updated when new versions are released.
            model: gemini-2.5-flash
