server:
  port: 9010

spring:
  ai:
    vertex:
      ai:
        api-key: ${GOOGLE_API_KEY}
        project-id: "gen-lang-client-0145362080"
        location: "asia-south1"
        gemini:
          chat:
            options:
              model: "gemini-2.0-flash"
