server:
  port: 9007

# --- MongoDB Configuration ---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/spenzr_groupexpense_db

# --- Keycloak JWT Configuration ---
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8180/realms/spenzr-realm
