server:
  port: 9007

spring:
  # All spring properties are nested under this single key
  data:
    mongodb:
      uri: mongodb://localhost:27017/spenzr_groupexpense_db
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/spenzr-realm
          
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # Add this line to stop sending class name headers
        spring.json.add.type.headers: false 

# Custom application properties remain at the top level
app:
  kafka:
    transactions-topic: "transactions"
