server:
  port: 9011

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/spenzr_suggestion_db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/spenzr-realm
