server:
  port: 9004

# --- All Spring properties are now under a single 'spring' key ---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spenzr_transaction_db
    username: anshulsharma
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/spenzr-realm
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # Add this line to stop sending class name headers
        spring.json.add.type.headers: false 

# --- Other top-level keys ---
management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  kafka:
    transactions-topic: "transactions"
    transaction-events-topic: "transaction-events"
