server:
  port: 9004

# --- Database Configuration ---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spenzr_transaction_db
    username: anshulsharma
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# --- Keycloak JWT Configuration ---
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8180/realms/spenzr-realm

# --- Actuator ---
management:
  endpoints:
    web:
      exposure:
        include: "*"


# --- Kafka Producer Configuration ---
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Use JsonSerializer to send our DTO as a JSON string
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Custom application properties
app:
  kafka:
    transactions-topic: "transactions"
