server:
  port: 9001

# --- Database Configuration ---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spenzr_user_db
    username: anshulsharma # PostgreSQL username
    password: postgres # PostgreSQL password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # In production, use 'validate' or a migration tool like Flyway/Liquibase
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# --- Keycloak JWT Configuration ---
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8180/realms/spenzr-realm # IMPORTANT: Replace with your Keycloak realm URL

# --- Actuator ---
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
