server:
  port: 9002

# --- Database Configuration ---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spenzr_preference_db
    username: anshulsharma # PostgreSQL username
    password: postgres # PostgreSQL password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# --- Keycloak JWT Configuration ---
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8180/realms/spenzr-realm

# --- Actuator ---
management:
  endpoints:
    web:
      exposure:
        include: "*"
